apiVersion: apps/v1
kind: Deployment
metadata:
  name: fp-part2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cm-pod
  template:
    metadata:
      labels:
        app: flask-cm-pod
    spec:
      containers:
        - name: flask-pod-fp
          image: amitgoldgh/python-flask-part2:latest
          ports:
            - containerPort: 5000
          env:
            - name: CONFIG_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: CONFIG_MESSAGE
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: API_KEY
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5