apiVersion: v1
kind: Service
metadata:
  name: cm-pod-service
spec:
  type: NodePort
  selector:
    app: flask-cm-pod
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080